services:
  # Backend API only for development
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
      - ./app:/app/app  # Hot reload for development
    environment:
      - PYTHONPATH=/app
      - APP_SECRET=${APP_SECRET}